# Generated by Django 5.0 on 2024-01-26 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sebacatalog', 'old_0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('nivel', models.IntegerField()),
                ('idcategoriaagrupa', models.IntegerField()),
                ('foto', models.TextField()),
                ('observaciones', models.TextField()),
                ('descuento_porcentaje', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DireccionEmpresas',
            fields=[
                ('iddireccionempresa', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('leadtime', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoImputaciones',
            fields=[
                ('idtipo_imputacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('idempresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=500)),
                ('habilitado', models.PositiveIntegerField()),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sebacatalog.direccionempresas')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('habilitado', models.PositiveIntegerField()),
                ('mail', models.CharField(max_length=500)),
                ('perfil', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sebacatalog.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('idpedido', models.AutoField(primary_key=True, serialize=False)),
                ('nro_pedido', models.BigIntegerField()),
                ('fecha_pedido', models.DateTimeField()),
                ('fecha_entrega', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sebacatalog.clientes')),
                ('direccionempresa_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sebacatalog.direccionempresas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sebacatalog.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.TextField()),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField()),
                ('descripcioncorta', models.TextField()),
                ('foto', models.TextField()),
                ('observaciones', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sebacatalog.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos_linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_producto', models.FloatField()),
                ('cantidad_producto', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sebacatalog.pedidos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sebacatalog.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Imputaciones',
            fields=[
                ('idImputacion', models.AutoField(primary_key=True, serialize=False)),
                ('nro_imputacion', models.CharField(max_length=30)),
                ('monto_imputacion', models.FloatField()),
                ('observacion', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sebacatalog.empresas')),
                ('tipo_imputacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sebacatalog.tipoimputaciones')),
            ],
        ),
    ]
